name: CI Workflow

on:
  push:
    branches:
      - develop
      - release/*
      - feature/*
  pull_request:
    branches:
      - develop
      - release/*
      - feature/*
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B test

      - name: Publish Test Report
        if: success() || failure()  # Always run this step, whether tests pass or fail
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/target/surefire-reports/*.xml'

  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # To ensure the actual PR commit is checked out
          fetch-depth: 0  # Full history for pull request analysis

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1328536289 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
